name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: [self-hosted, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2

      - name: Install dependencies
        uses: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm run test